from abc import ABC, abstractmethod
class CryptoBackend(ABC):
    @abstractmethod
    def initialize_profiles(self): ...
    @abstractmethod
    def get_public_context(self, profile_id): ...
    @abstractmethod
    def encrypt_update(self, flat_update, profile_id): ...
    @abstractmethod
    def multiply_plain(self, encrypted_update, weight): ...
    @abstractmethod
    def add_ciphertexts(self, ciphertexts): ...
    @abstractmethod
    def serialize(self, ciphertext): ...
    @abstractmethod
    def deserialize(self, payload, profile_id): ...
