from abc import ABC,abstractmethod
class DefenseStrategy(ABC):
    @abstractmethod
    def initialize(self, model, crypto_backend, proxy_loader): ...
    @abstractmethod
    def get_profile_for_round(self, round_id): ...
    @abstractmethod
    def after_aggregate(self, previous_model, candidate_model, current_profile_id, round_id): ...
